---
title: "Homework"
author: "Lluis Ramon"
date: "20 de abril de 2015"
output: html_document
---

# Introduction

TODO(Mathieu): Reduced version

Cattle are an important economic resource and also a major health factor in many countries. Therefore preventing diseases in a herd is vital. 

In this study we focus our interest on the parasite of trypanosomosis which can lead to the death of a cow. This disease, transmitted by the tsetse flies, causes an infection characterized by fever, loss of appetite and anemia, which can lead to death depending on different factors.

One medicine, the Berenil, is used to cure the infected cattle. The aim of this research is to determine the efficiency of different doses of Berenil. Finding the most efficient dose, if such a dose exists, is critical when it comes to save both cattle and money. Here lies all the interest of our study. 

To determine if a cow is ill or not a binary variable will be studied. This indicator can be 1 for a healthy cow or 0 for a sick one.



# Objective

The aim of this study is to assess the efficacy of different doses of Berenil in cattle infected with the trypanosomosis parasite.


# Dataset

A cohort of 10 different cows infected by trypanosomosis parasite was selected for the study. Each  Berenil dose (low, medium and high) was administrated three times (time 1, 2 or 3) for each animal. PCV was reported each time as well as the number of calves it had before being infected.

The variables reported for this study are presented below.

* Id: Each cow has its own id. From 1 to 10. _(id)_
* PCV: Binary variable. _(pcv.b)_
* Dose: H High, M Medium L low. _(dose)_
* Time: From 1 to 3. _(time)_
* Number of birth: From 2 to 8. _(nbirth)_

Since the gathering process of the data was unknown, several assumptions were needed.

* Each time PCV is obtained before the treatment. Therefore the effect of the third dose could not be evaluated.
* Dose is assigned randomly in time to the cow.
* For a given cow, the previous treatments (high, medium or low) do not affect the following ones.
* Time intervals are the same and fixed.


# Outcome categorization

The binary response was related with a cow being healthy or unhealthy. Taking this into considertation, the outcome was categorized using the following criteria:

* [Literature review][]*: A healthy cow is estimated to have a PCV value ranging from 24 to 46.
* Practical Modeling: As the binary response should be modeled in following sections, a suitable one was searched. To this end, a trial and error with a cutoff ranging from 20 to 24 was explored.

The threshold between healthy and unhelathy cow was set at a PCV value of 20. If the PCV value was bigger it was categorized as healthy, if it was lower or equal it was cathegorized as unhelathy.

TODO(Mathieu): Improve text
TODO(Gerard): Table to LaTeX. (You can remove Missing row if you want)

```{r}
#            Time 1 Time 2 Time 3
#   Healthy       28     15      2
#   Unhealthy      1     12     18
#   <NA>           1      3     10
```


[Literature review]:http://research.vet.upenn.edu/Dairy/ClinicalPathology/tabid/3848/Default.aspx



# Statistical methods

The methods used in the statistical analyses are detailed in this section. First a Generalized Estimating Equations and latter a Generalized Linear Mixed Model. An exploratory data analysis was performed before those regression methods.

## GEE

The response variable was the cathegorized PCV to detect healthy and unhelathy cows. As we wanted to estimate the effect of dose in healthy/unhelathy cows in time, these two variables were included in the model.

From this initial model, a forward step-wise method was carried for the model selection, including additional covariates or interactions between them. The models were compared quasilikelihood ratio test when nested and with QuasiLikelihood Information Criteria (Pan 2001) when non-nested.

## GLMM

TODO(Mathieu)

IN order to take into account the specific effect due to the cow itself we had to introduce random effects in our model. To do that we performed a Generalised Linear Mixed Model. We kept the fixed effects found in the previous part and add random effects on the intercept and the time. Since we have two way of grouping our data we have a random effect for the id and among the values of a given cow we have random effects for the kind of dose that was used. 


## Transition Models

TODO(Lluis): Add model information.
TODO(All): Include pros/cons with our data. Decide if our data could be modeled using this kinds of models.

# Results

## GEE 

TODO(Lluis)

## Random effects model

TODO(Mathieu)

# Missing Data Analysis

TODO(Gerard): Missing exploration

# Limitations and Further research

* Jacknife estimators for small sample better than sandwhich estimator

> Jackknife variance estimators are preferable to the sandwich estimator in case of a small number of clusters. (Højsgaard, Halekoh, Yan 2006)

* Compre a new factor L and M dose against H dose
* Perfect Separation Problem with gee

> It apeared when using a 22 PCV value threshold for healthy or unhealthy cow.

* Compare GEE model with GLMM. Coeficients and SE.

# Bibliography

TODO(Gerard): Normalize citations

* [Pan 2001, Biometrics, Akaike's Information Criterion in Generalized Estimating Equations.][]
* [Højsgaard, Halekoh, Yan 2006, The R Package geepack for Generalized Estimating  Equations.][]
* [Hardin & Hilbe 2002, Generalized Estimating Equations][]

[Pan 2001, Biometrics, Akaike's Information Criterion in Generalized Estimating Equations.]: http://www.jstor.org/stable/2676849?seq=2#references_tab_contents
[Højsgaard, Halekoh, Yan 2006, The R Package geepack for Generalized Estimating  Equations.]: http://www.jstatsoft.org/v15/i02/paper
[Hardin & Hilbe 2002, Generalized Estimating Equations]: http://books.google.es/books/about/Generalized_Estimating_Equations.html?id=wxl7ajq8ymYC&redir_esc=y